chore: check minimum suported rust version and prompt user to update if lower

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,8 +1,8 @@
 #!/usr/bin/env sh
 
-# https://github.com/eitsupi/prqlr/blob/main/configure
 export PATH="$PATH:$HOME/.cargo/bin"
 
+# check if cargo is installed
 if [ ! "$(command -v cargo)" ]; then
     echo "----------------------- [RUST NOT FOUND]---------------------------"
     echo "The 'cargo' command was not found on the PATH. Please install rustc"
@@ -12,6 +12,18 @@ if [ ! "$(command -v cargo)" ]; then
     echo " - Debian/Ubuntu: apt-get install cargo"
     echo " - Fedora/CentOS: dnf install cargo"
     echo " - macOS: brew install rustc"
+    echo "-------------------------------------------------------------------"
+    echo ""
+    exit 1
+fi
+
+# Check rustc version
+REQUIRED_RUSTC_VERSION="1.67.1"
+INSTALLED_RUSTC_VERSION=$(rustc --version | awk '{print $2}')
+if [ "$(printf '%s\n' "$REQUIRED_RUSTC_VERSION" "$INSTALLED_RUSTC_VERSION" | sort -V | head -n1)" != "$REQUIRED_RUSTC_VERSION" ]; then
+    echo "----------------------- [RUST VERSION TOO LOW]---------------------------"
+    echo "The installed rustc version is $INSTALLED_RUSTC_VERSION. Please install"
+    echo "rustc version $REQUIRED_RUSTC_VERSION or higher."
     echo "-------------------------------------------------------------------"
     echo ""
     exit 1
